[package]
name = "pollocad-occt"
version = "0.1.0"
edition = "2021"
links = "occt"

[dependencies]
bitflags = "1.3"
cpp = "0.5"
raw-window-handle = "0.5"

[build-dependencies]
bindgen = "0.64"
cpp_build = "0.5"
